[build-system]
requires = ["uv_build>=0.6"]
build-backend = "uv_build"

[project]
name = "moops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.23.1",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.1.0",
    "pyright>=1.1.409",
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = ["src", "."]

[tool.pyright]
typeCheckingMode = "strict"
include = ["src", "tests"]
extraPaths = ["src", ".", "examples"]

[tool.uv.sources]
moops = { workspace = true }

[tool.ruff.lint]
select = ["E", "F", "I", "B", "RUF", "C4", "SIM", "N", "Q", "TID", "UP", "PT", "RET"]

[tool.ruff.lint.per-file-ignores]
"examples/*.py" = ["F401", "F841", "B018"]
